build:
  environment:
    php:
      version: 7.0
filter:
  excluded_paths: [docs/*, tests/*, vendor/*]
tools:
  php_code_sniffer:
      enabled: true
      config:
        standard: "PSR2"
      filter:
        excluded_paths: [docs/*, tests/*, vendor/*]
  php_mess_detector:
      enabled: true
      filter:
        excluded_paths: [docs/*, tests/*, vendor/*]
  php_cpd:
    enabled: true
    excluded_dirs: [docs/*, tests/*, vendor/*]
    filter:
      excluded_paths: [docs/*, tests/*, vendor/*]
  php_hhvm:
    enabled: true
    filter:
      excluded_paths: [docs/*, tests/*, vendor/*]
  php_loc:
    enabled: true
    excluded_dirs: [docs/*, tests/*, vendor/*]
  php_pdepend:
    enabled: true
    excluded_dirs: [docs/*, tests/*, vendor/*]
  php_analyzer:
    enabled: true
    filter:
      excluded_paths: [docs/*, tests/*, vendor/*]