site_name: 'Sikker PHP Package'
site_url: http://norse.blue
site_author: 'Norse Blue'
site_favicon: favicon.ico
copyright: '2016 © Norse Blue'
repo_url: https://github.com/NorseBlue/Sikker
repo_name: 'GitHub'
theme: readthedocs
pages:
  - Home: 'index.md'
  - About:
    - License: 'about/license.md'
  - Package:
    - Installation: 'package/installation.md'